---
output:
  
  word_document: default

---

```{r message=FALSE, warning=FALSE, echo=FALSE}

library(tidyverse)
library(rstatix)
library(broom)
library(ggsignif)
library(ggplot2)
library(kableExtra)
library(readxl)
library(flextable)
library(lubridate)

library(tidyverse)
library(readxl)
library(adegenet)
library(poppr)
library(radiator)

```

```{r message=FALSE, warning=FALSE, echo=FALSE}

Data_2111 <- read.genepop("X:/2111_F1F2D_BKT/2111analysis/Thometz_scripts/2111_genepop.gen", 
                          ncode = 3L, 
                          quiet = FALSE)

Samples_2111 <- read_delim("X:/2111_F1F2D_BKT/2111analysis/Thometz_scripts/Samples_2111.csv") %>% 
  filter(SampleID %in% rownames(Data_2111@tab)) %>% 
  arrange(match(SampleID, rownames(Data_2111@tab)))
  
#### Read in BestConfig files #### (manually cleaned them up in notepad++)
config_2019 <- read_delim("X:/2111_F1F2D_BKT/2111analysis/Thometz_scripts/Analyses/Colony_3_runs/Output_files/2020/cleaned_up.BestConfig_Ordered") %>% 
  select(-ClusterIndex)

config_2020 <- read_delim("X:/2111_F1F2D_BKT/2111analysis/Thometz_scripts/Analyses/Colony_3_runs/Output_files/2021/cleaned_up.BestConfig_Ordered") %>% 
  select(-ClusterIndex)

config_2021 <- read_delim("X:/2111_F1F2D_BKT/2111analysis/Thometz_scripts/Analyses/Colony_3_runs/Output_files/2022/cleaned_up.BestConfig_Ordered") %>% 
  select(-ClusterIndex)

# Bind them together to make tidy config df
temp_wild <- Samples_2111 %>%
  select(SampleID, Cohort, Year) %>%
  filter(Cohort == "Wild") %>% 
  rename(OffspringID = SampleID,
         Offspring_cohort = Cohort,
         Offspring_year = Year)

temp_parents <- Samples_2111 %>%
  select(SampleID, Cohort, Year) %>%
  filter(Cohort != "Wild") %>% 
  rename(ParentID = SampleID,
         Parent_cohort = Cohort,
         Parent_year = Year)

config_all <- config_2019 %>% 
  bind_rows(config_2020) %>% 
  bind_rows(config_2021) %>% 
  pivot_longer(cols = c(FatherID, MotherID), 
               names_to = "Parent_type", 
               values_to = "ParentID") %>% 
  left_join(temp_parents) %>% 
  left_join(temp_wild) %>% 
  select(-Parent_type) %>% 
  drop_na()

N_offspring <- config_all %>% 
  group_by(ParentID) %>% 
  summarize(n_offspring = n_distinct(OffspringID)) %>% 
  left_join(temp_parents) %>% 
  rename(Group = Parent_cohort,
         Year_stocked = Parent_year) %>% 
  select(ParentID, Group, Year_stocked, n_offspring) %>% 
  arrange(desc(n_offspring))

```

```{r message=FALSE, warning=FALSE, echo=FALSE}

N_offspring %>% 
  flextable() %>% 
  fontsize(size = 11, part = "all") %>% 
  colformat_num(big.mark = "") %>% 
  autofit()

```
